const PROJECT_PRICE = 1_200;
const FREELANCER_COMMISSION = 0.10;
const MAX_PROJECTS = 10;
console.log("=== Operaciones básicas ===");
const activeProjects = 6;
const totalRevenue = PROJECT_PRICE * activeProjects;
console.log("Ingresos totales:", totalRevenue);
const platformEarnings = totalRevenue * FREELANCER_COMMISSION;
console.log("Ganancia plataforma:", platformEarnings);
const remainingProjects = MAX_PROJECTS - activeProjects;
console.log("Proyectos disponibles:", remainingProjects);
console.log("");
console.log("=== Asignación compuesta ===");
let accumulatedEarnings = 0;
accumulatedEarnings += 500;
console.log("Tras primer proyecto:", accumulatedEarnings);
accumulatedEarnings += 700;
console.log("Tras segundo proyecto:", accumulatedEarnings);
accumulatedEarnings *= 0.90;
console.log("Después de comisión:", accumulatedEarnings);
console.log("");
console.log("=== Validaciones con === ===");
const completedProjects = 6;
const isAllCompleted = completedProjects === MAX_PROJECTS;
console.log("¿Todos los proyectos completados?", isAllCompleted);
const hasPendingProjects = completedProjects < MAX_PROJECTS;
console.log("¿Hay proyectos pendientes?", hasPendingProjects);
console.log("");
console.log("=== Condiciones lógicas ===");
const isFreelancerVerified = true;
const projectBudget = 1_200;
const canTakeProject = isFreelancerVerified && projectBudget >= 1_000;
console.log("¿Puede tomar el proyecto?", canTakeProject);
const isHighValueProject = projectBudget > 2_000 || isFreelancerVerified;
console.log("¿Proyecto de alto valor o freelancer verificado?", isHighValueProject);
console.log("");
console.log("=== Resumen ===");
console.log("Proyectos activos:", activeProjects);
console.log("Ingresos totales:", totalRevenue);
console.log("Ganancia plataforma:", platformEarnings);
console.log("Proyectos disponibles:", remainingProjects);
console.log("");